//
//  CoreDataManager.h
//  ProductBrowserApp
//
//  Created by Jibin Raju on 12/01/16.
//  Copyright © 2016 Sogeti B.V. All rights reserved.
//

#import <Foundation/Foundation.h>

/*
 * CoreData handler class and all core data default implementation generated by xcode IDE.
 * Coredata create a persistence for offline support
 */

@interface CoreDataManager : NSObject

/*
 * Below core data properites are generated by XCode.
 */
@property (readonly, strong, nonatomic) NSManagedObjectContext *managedObjectContext;
@property (readonly, strong, nonatomic) NSManagedObjectModel *managedObjectModel;
@property (readonly, strong, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;

/*
 * This is also a xcode generated function
 * Function will save current context objects into the persisitance cooredinate.
 * @parameter : NO Arguments
 * @return type : void
 */
+ (instancetype) sharedInstance;


/*
 * This is also a xcode generated function
 * Function will save current context objects into the persisitance cooredinate.
 * @parameter : NO Arguments
 * @return type : void
 */
- (void) saveContext;

/*
 * Create a new object of productInformation entity and return it
 * @parameter : NO Arguments
 * @return type : NSManagedObject, if any error occured at creation time it will return 'nil'.
 */
- (NSManagedObject *) createProductInformationEntity;

/*
 * Search product name from the core data and return the find object
 * @parameter : productName, to search
 * @return type : NSManagedObject, search result may be managed object otherwise nil.
 */
- (NSManagedObject *) searchProductName: (NSString *) productName;

/*
 * Function create a new fetched results controller to efficiently manage the results returned from a Core Data fetch request to provide data.
 * especially fetch result controller and UITableView object will work in a good harmony and this function special for that pupose only.
 * @parameter : NO Arguments
 * @return type : NSFetchedResultsController, if any error occured while creation time it will return nil.
 */
- (NSFetchedResultsController *) createNewFetchedResultsControllerForProductInformation;

@end
